apiVersion: apps/v1

kind: Deployment

metadata:
  name: practica-ci
  labels:
    app: practica-ci

spec:
  replicas: 1
  selector:
    matchLabels:
      app: practica-ci
  template:
    metadata:
      labels:
        app: practica-ci
    spec:
      containers:
      - name: practica-ci-container
        image: pau7rr/practica-ci-server:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: practica-ci-service
spec:
  selector:
    app: practica-ci
  ports:
  - name: name-of-service-port
    targetPort: 3000
    port: 3000
    nodePort: 30253
    protocol: TCP
  selector:
    app: practica-ci
  type: NodePort