apiVersion: apps/v1

kind: Deployment

metadata:

  name: practica-ci

  labels:

    app: practica-ci

spec:

  replicas: 1

  selector:

    matchLabels:

      app: practica-ci

  template:

    metadata:

      labels:

        app: practica-ci

    spec:

      containers:

      - name: practica-ci-container

        image: pau7rr/practica-ci-server:latest

        ports:

        - containerPort: 80
