name: Integration Test CI

on:
  workflow_run:
    workflows: ["Build and Test CI"]
    branches: [main]
    types: 
      - completed

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: develop
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: touch .env.test.local \
        && echo "PORT=${{ vars.PORT }}" >> .env.test.local \
        && echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env.test.local \
        && echo "LOG_FORMAT=${{ vars.LOG_FORMAT }}" >> .env.test.local \
        && echo "LOG_DIR=${{ vars.LOG_DIR }}" >> .env.test.local \
        && echo "ORIGIN=${{ vars.ORIGIN }}" >> .env.test.local \
        && echo "CREDENTIALS=${{ vars.CREDENTIALS }}" >> .env.test.local

    - run: npm install
    - run: npm run test:integration
