name: Kubernetes deploy

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    environment: develop
    runs-on: ubuntu-latest

    steps:
    - name: Install oc
      uses: redhat-actions/oc-installer@v1
      with:
        oc_version: '4.6'

    - name: Test oc
      run: oc version --client

    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      env:
        OPENSHIFT_USER: ${{ secrets.OPENSHIFT_USER }}
        OPENSHIFT_NAMESPACE: pau7rr-dev
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}

    - name: Deploy new version
      uses: actions/checkout@v3
      run: kubectl apply -f ./deployment.yaml