name: Kubernetes deploy

on:
  workflow_run:
    workflows: ["Docker Image CI", "Test CI", "Integration Test CI"]
    branches: [main]
    types: 
      - completed

jobs:

  build:
    environment: develop
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install oc
      uses: redhat-actions/oc-installer@v1
      with:
        oc_version: '4.6'

    - name: Test oc
      run: oc version --client

    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      env:
        OPENSHIFT_USER: ${{ secrets.OPENSHIFT_USER }}
        OPENSHIFT_NAMESPACE: pau7rr-dev
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}

    - name: Delete actual deployment
      run: kubectl delete deployments practica-ci
    - name: Delete actual service
      run: kubectl delete services practica-ci-service
    - name: Deploy new version
      run: kubectl apply -f ./deployment.yaml